### ISSUE TITLE
Download csv is not available.

### ISSUE THREAD

**Issue by junjihashimoto** [oasysgames/oasys-blockscout#9]
Download csv is not available.
In the site of https://scan.oasys.games/, we can not download transactions with csv format.

### Environment

https://scan.oasys.games/

### Steps to reproduce

1, Open https://scan.oasys.games
2, Click an address.
3, Click a "Download CSV" link in the transactions tab.
4, Then, we can see the error as below.

![image](https://user-images.githubusercontent.com/2469618/215624650-6c59aaaa-dcbe-429e-b758-414dd56b0a4c.png)

### Expected behaviour

Download a csv file of transactions.

### Actual behaviour

Download csv is not available.

**Comment by fromreto** [comment]
@junjihashimoto 
Thanks for your valuable feedback. 
We have tried multiple ways on csv settings with ReCaptcha enterprise, and it having some issues while fixing 
setting up keys. 
Our team is working on it, but we can provide you with a better idea about this issue. 

We will notify you with furthermore related updates.
